"""chat messages

Revision ID: 180049ae2f6b
Revises: 4d923f3cedea
Create Date: 2026-09-21 17:56:58.972409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180049ae2f6b'
down_revision = '4d923f3cedea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auction_id', sa.Uuid(), nullable=False),
    sa.Column('bidder_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_auction_id'), ['auction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_auction_id'))

    op.drop_table('chat_messages')
    # ### end Alembic commands ###
