"""livebid schema

Revision ID: 4d923f3cedea
Revises: 
Create Date: 2026-09-21 16:47:32.460752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d923f3cedea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('auctions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starting_bid', sa.Integer(), nullable=False),
    sa.Column('minimum_increment', sa.Integer(), nullable=False),
    sa.Column('current_bid', sa.Integer(), nullable=False),
    sa.Column('highest_bidder_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'LIVE', 'ENDED', 'CANCELLED', name='auction_status'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['highest_bidder_id'], ['bidders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_id', 'sequence')
    )
    with op.batch_alter_table('auction_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auction_events_auction_id'), ['auction_id'], unique=False)

    op.create_table('auction_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auction_id', sa.Uuid(), nullable=False),
    sa.Column('bidder_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_id', 'bidder_id')
    )
    with op.batch_alter_table('auction_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auction_participants_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_participants_bidder_id'), ['bidder_id'], unique=False)

    op.create_table('bids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auction_id', sa.Uuid(), nullable=False),
    sa.Column('bidder_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_request_id'), ['request_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_request_id'))
        batch_op.drop_index(batch_op.f('ix_bids_auction_id'))

    op.drop_table('bids')
    with op.batch_alter_table('auction_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_participants_bidder_id'))
        batch_op.drop_index(batch_op.f('ix_auction_participants_auction_id'))

    op.drop_table('auction_participants')
    with op.batch_alter_table('auction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_events_auction_id'))

    op.drop_table('auction_events')
    op.drop_table('auctions')
    op.drop_table('bidders')
    # ### end Alembic commands ###
